services:
  parser:
    image: ubuntu-server:0.0.1
    container_name: webservice
  core:
    build: .
    ports:
      - "9200:9200"
      - "9600:9600"
      - "10601:10601"
      - "27017:27017"
    volumes:
      - ./opt/:/opt
    image: ubuntu-server:0.0.1