services:
  base:
    build: docker/base/
    image: gcs-base:0.1
  webservice:
    cap_add:
      - NET_ADMIN
    build: .
    network_mode: "host"
    volumes:
      - "./opt:/opt/gcs"
    image: gcs-main:0.1
    depends_on:
      - base
    