services:
  base:
    build: docker/base/
    image: gcs-base:0.1
  webservice:
    cap_add:
      - NET_ADMIN
    build: .
    ports:
      - "9200:9200"
      - "9600:9600"
      - "10601:10601"
      - "27017:27017"
      - "14550-20000:14550-20000"
    volumes:
      - /home/slava/Documents/TestWebSeervice/opt:/opt/gcs
    image: gcs-main:0.1
    depends_on:
      - base
    