
cluster.name: opensearch-cluster

node.name: opensearch-node1

network.host: 0.0.0.0

discovery.type: single-node

opensearch.ssl.http.enabled: true

opensearch.ssl.http.pemcert_filepath: /path/to/your/certificate.pem
opensearch.ssl.http.pemkey_filepath: /path/to/your/private-key.pem
opensearch.ssl.http.pemtrustedcas_filepath: /path/to/your/ca-certificate.pem

opensearch.ssl.http.enabled_protocols: [ "TLSv1.2" ]

# Set the supported cipher suites
opensearch.ssl.http.ciphers: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"

# Optional: Enable mutual authentication (client certificates)
# opensearch.ssl.http.clientauth_mode: optional
# opensearch.ssl.http.pemcert_filepath: /path/to/client_certificate.pem
# opensearch.ssl.http.pemkey_filepath: /path/to/client_private_key.pem

# Enable TLS/SSL for transport layer
opensearch.ssl.transport.enabled: true
opensearch.ssl.transport.pemcert_filepath: /path/to/your/certificate.pem
opensearch.ssl.transport.pemkey_filepath: /path/to/your/private-key.pem
opensearch.ssl.transport.pemtrustedcas_filepath: /path/to/your/ca-certificate.pem

# Cluster settings
opensearch.cluster.routing.allocation.disk.threshold_enabled: true
opensearch.cluster.routing.allocation.disk.watermark.low: 85%
opensearch.cluster.routing.allocation.disk.watermark.high: 90%
opensearch.cluster.routing.allocation.disk.watermark.flood_stage: 95%