
cluster.name: opensearch-cluster

node.name: opensearch-node1

network.host: 0.0.0.0

discovery.type: single-node

plugins:
  security:
    config_index_name: .opendistro_security
    ssl:
      http:
        enabled: true
        pemcert_filepath: /opt/gcs/opensearch/config/certs/server-cert.pem
        pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
        pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem
      transport:
        enabled: true
        pemcert_filepath: /opt/gcs/opensearch/config/certs/server-cert.pem
        pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
        pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem
        enforce_hostname_verification: false
    allow_unsafe_democertificates: true
    authcz:
      admin_dn:
        - "CN=mydomain.com,O=Example Company,L=Los Angeles,ST=California,C=US"

# Optional: Enable mutual authentication (client certificates)
# opensearch.ssl.http.clientauth_mode: optional
# opensearch.ssl.http.pemcert_filepath: /path/to/client_certificate.pem
# opensearch.ssl.http.pemkey_filepath: /path/to/client_private_key.pem

# # Cluster settings
# opensearch.cluster.routing.allocation.disk.threshold_enabled: true
# opensearch.cluster.routing.allocation.disk.watermark.low: 85%
# opensearch.cluster.routing.allocation.disk.watermark.high: 90%
# opensearch.cluster.routing.allocation.disk.watermark.flood_stage: 95%