
cluster.name: opensearch-cluster

node.name: opensearch-node1

network.host: 0.0.0.0

discovery.type: single-node

opensearch.ssl.http.enabled: true
plugins.security.authcz.admin_dn:
  - C = US, ST = California, L = Los Angeles, O = Example Company, CN = mydomain.com

opensearch.ssl.http.pemcert_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
opensearch.ssl.http.pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
opensearch.ssl.http.pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem

opensearch.ssl.http.enabled_protocols:
  - "TLSv1.1"
  - "TLSv1.2"

# Set the supported cipher suites
opensearch.ssl.http.ciphers:
  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
  - "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"

# Optional: Enable mutual authentication (client certificates)
# opensearch.ssl.http.clientauth_mode: optional
# opensearch.ssl.http.pemcert_filepath: /path/to/client_certificate.pem
# opensearch.ssl.http.pemkey_filepath: /path/to/client_private_key.pem

# Enable TLS/SSL for transport layer
opensearch.ssl.transport.enabled: true
opensearch.ssl.transport.pemcert_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
opensearch.ssl.transport.pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
opensearch.ssl.transport.pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem

# Cluster settings
opensearch.cluster.routing.allocation.disk.threshold_enabled: true
opensearch.cluster.routing.allocation.disk.watermark.low: 85%
opensearch.cluster.routing.allocation.disk.watermark.high: 90%
opensearch.cluster.routing.allocation.disk.watermark.flood_stage: 95%