
cluster.name: opensearch-cluster

node.name: opensearch-node1

network.host: 0.0.0.0

discovery.type: single-node

plugins:
  security:
    ssl:
      http:
        enabled: true
        pemcert_filepath: /opt/gcs/opensearch/config/certs/server-cert.pem
        pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
        pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem
      transport:
        enabled: true
        pemcert_filepath: /opt/gcs/opensearch/config/certs/server-cert.pem
        pemkey_filepath: /opt/gcs/opensearch/config/certs/server-key.pem
        pemtrustedcas_filepath: /opt/gcs/opensearch/config/certs/ca-cert.pem
        enforce_hostname_verification: false
    allow_unsafe_democertificates: true
    authcz:
      admin_dn:
        - "CN=mydomain.com,O=Example Company,L=Los Angeles,ST=California,C=US"
#     nodes_dn:
#       - 'CN=opensearch-node1,O=ARK,L=YANGON,ST=YANGON,OU=ENGINEERING,C=CA'
    audit:
      type: internal_opensearch
#     enable_snapshot_restore_privilege: true
#     check_snapshot_restore_write_privileges: true
#     restapi:
#       roles_enabled: ["all_access", "security_rest_api_access"]

opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.config.disabled_transport_categories: NONE

# cluster.routing.allocation.disk.threshold_enabled: false
    